### ISSUE TITLE
RocketJob not compatible with ActiveJob

### ISSUE THREAD

**Issue by hishammalik** [rocketjob/rocketjob#12]
I am running rocketjob with activejob 4.2.8. If I specify :rocket_job as the queue_adapter, I get an undefined enqueue method error.
`config.active_job.queue_adapter = :rocket_job`

To work around it, I explicitly initialized an instance of RocketJobAdapter like:
`config.active_job.queue_adapter = ActiveJob::QueueAdapters::RocketJobAdapter.new` 

However, with this, I get the error:
Mongoid::Errors::UnknownAttribute: 
message:
  Attempted to set a value for 'job_class' which is not allowed on the model ActiveJob::QueueAdapters::RocketJobAdapter::JobWrapper.

**Comment by reidmorrison** [comment]
Upgraded the ActiveJob adapter to work with Rocket Job v3, can you try the latest code in the master branch?

~~~ruby
gem 'rocketjob', git: 'https://github.com/rocketjob/rocketjob.git'
~~~
