### ISSUE TITLE
ActiveJob & cron plugin > undefined method `after_abort'

### ISSUE THREAD

**Issue by HLFH** [rocketjob/rocketjob#14]
Hi,

I have a RatesJob:
```ruby
class RatesJob <  ApplicationJob
  queue_as :default
  include RocketJob::Plugins::Cron

  self.cron_schedule      = '*/15 * * * * * UTC'

  def perform
    ...
  end
end
```

And an ApplicationJob:
```ruby
class ApplicationJob < ActiveJob::Base
end
```

But it seems with your cron plugin, I can't perform the job with **_undefined method `after_abort'_** issue.
```bash
irb(main):003:0> RatesJob.first.update_attributes(run_at: nil)
NoMethodError: undefined method `after_abort' for RatesJob:Class
        from app/jobs/rates_job.rb:3:in `include'
        from app/jobs/rates_job.rb:3:in `<class:RatesJob>'
        from app/jobs/rates_job.rb:1:in `<top (required)>'
        from (irb):3
```

Can you please help?

Also, I don't see any ActiveJob documentation on [your website](http://rocketjob.io/).

Thanks,
HLFH

**Comment by reidmorrison** [comment]
ActiveJob does not support using Cron, it supplies a lowest common denominator API.

Cron works only if you use RocketJob directly. There are examples in the RocketJob documentation.

ActiveJob itself is documented on the Rails site.

**Comment by HLFH** [comment]
If I use `sidekiq`, I can have `[sidekiq-cron](https://github.com/ondrejbartas/sidekiq-cron)` that is using `[rufus-scheduler](https://github.com/jmettraux/rufus-scheduler)`. `sidekiq-cron` can be used with ActiveJob.
Can we use ` include RocketJob::Plugins::Rufus`, on a specified job, **using ActiveJob** with RocketJob queueing backend?

**Comment by reidmorrison** [comment]
No. ActiveJob does not support scheduled jobs.
Rocket Job supports scheduled jobs.
