### ISSUE TITLE
Middleware support

### ISSUE THREAD

**Issue by chrisgogreen** [rocketjob/rocketjob#4]
Do you plan to support custom middleware?

**Comment by reidmorrison** [comment]
We have added behavior to our own internal jobs by creating new base classes that new jobs can derive from. Additionally we use mix-ins to sprinkle in specific behavior where needed.

For example:
```ruby
# Abstract class to add custom behavior
class FileJob < RocketJob::Job
  def before_perform
     # Custom file specific behavior, for example upload a file for processing
  end
end
```

Now we can create any job that includes the above specialized behavior by deriving it from `FileJob`:
```ruby
# MyJob now inherits the behavior in FileJob
class MyJob < FileJob
  def perform
    # process data
  end
end
```

This approach follows inheritance hierarchies allowing any job's behavior to be shared or specialized in any way without affecting jobs that do not require or want that behavior.

Not only can `FileJob` modify the behavior of what is processed, it has full access to all workflow related events, to take action when an event occurs. `FileJob` can also change state transitions if required.

For example:
```ruby
# Abstract class to add custom behavior
class FileJob < RocketJob::Job
  # Add a custom property that all file jobs can use
  key :file_name, String

  def before_perform
     # Custom file specific behavior, for example upload a file for processing
     # file_name is available in any method in this job:
     puts file_name
  end

  def before_fail
     # Send an email, or take other action when a job fails
  end
end
```

`rocketjob-pro` makes extensive use of the above extensibility features to create a powerful batch processing solution built on top of `RocketJob::Job`.

To mix-in specific behavior into a Job:
```ruby
class MyJob < RocketJob::Job
  # Create a singleton job so that only one instance is ever queued or running at a time
  include RocketJob::Concerns::Singleton

  def perform
    # process data
  end
end
```

Queue the job, supplying the `file_name` that was declared and used in `FileJob`:
```ruby
MyJob.create!(file_name: 'abc.csv')
```

I definitely need to add more documentation about this capability.

To help me ensure we are on the right track, what is the use case you want to solve?

**Comment by reidmorrison** [comment]
I added documentation on the extensibility features of RocketJob. I looked into the Sidekiq Middleware capabilities and did not find any relevant features that the extensibility features do not address.
http://rocketjob.io/api.html

Let us know your specific use-case for middleware so that we can be sure it is being addressed in rocketjob.
