### ISSUE TITLE
uninitialized constant RocketJob::SlicedJob

### ISSUE THREAD

**Issue by chrisgogreen** [rocketjob/rocketjob#5]
When I access http://localhost:3000/rocketjob/jobs/running I get this error:

```txt
NameError at /jobs/running
uninitialized constant RocketJob::SlicedJob
```

**Comment by reidmorrison** [comment]
Appears it is looking for a pro feature.
Can you send me the entire stack trace?

I will start up a mission control instance locally without rocket pro installed.

**Comment by reidmorrison** [comment]
Searching the code base I can see the issue. Will have it resolved shortly

**Comment by reidmorrison** [comment]
Released a fix to remove the dependency, please run `bundle update rocketjob_mission_control` and try again.
