### ISSUE TITLE
silence error on fresh install?

### ISSUE THREAD

**Issue by rjrobinson** [rocketjob/rocketjob#7]
trying to demo this out n an app to replace Resque. Followed the install instructions, and I'm getting 
`undefined method 'silence_logger' for #<SemanticLogger::Logger:0x007fb783162a28>`

Im trying to find the reference in the code, but alas, no such luck

**Comment by reidmorrison** [comment]
Can you include the full stack trace so that we can see where the call is coming from?
I searched all the Rocket Job source repos and Rails 5 for this method and could not find it.

Or, try installing the `rails_semantic_logger` gem which will patch rails calls like this.

**Comment by reidmorrison** [comment]
Ah, it appears that Active Record's Session Store calls `silence_logger` instead of `silence`.

I added an alias to [Semantic Logger](https://github.com/rocketjob/semantic_logger) to map `silence_logger` to `silence`.

Two ways to try it out, add the following line to Gemfile:
~~~ruby
gem 'semantic_logger', git: 'https://github.com/rocketjob/semantic_logger.git'
~~~

Or, for now add the following line in application.rb:
~~~ruby
SemanticLogger::Logger.send(:alias_method, :silence_logger, :silence)
~~~

**Comment by rjrobinson** [comment]
Yep. The latter sure did it. 

Now... about that web interface. Have you ever had issues where the layout/css seemed to be all "funky"

**Comment by rjrobinson** [comment]
<img width="1419" alt="screen shot 2016-05-06 at 7 09 46 pm" src="https://cloud.githubusercontent.com/assets/3730551/15088174/312c1650-13be-11e6-938c-38e42c7a0dbd.png">

**Comment by rjrobinson** [comment]
I've tried all of the browsers.

**Comment by reidmorrison** [comment]
It looks like some kind of style sheet issue. I will try to reproduce it on the plane tomorrow, but suspect I will need help from our Web developers.

What version of Rails are you running on? That will give me a good place to start.

**Comment by rjrobinson** [comment]
Awesome! Its `rails -v 4.2.5.1`

**Comment by reidmorrison** [comment]
We are still researching what could be causing the style sheet clash between the application and the Rails Engine.

Can you install a standalone Rocket Mission Control instance in the meantime?
http://rocketjob.io/installation.html

**Comment by rjrobinson** [comment]
Yep. Im getting a load_config error. Looking through the source code, I cant find this method

```shell
$ RocketJob::CLI.load_config('development', 'config/mongo.yml')
NoMethodError: undefined method `load_config' for RocketJob::CLI:Class
```

Which is what Im guessing would cause the 

```
undefined method `collection' for nil:NilClass
``` 
 error in the standalone `localhost:3000/rocketjob` 

Im not sure if im missing some dependencies. But I have tried to update and reinstall all of the gems. I even tried on a different system, and I am still getting the same errors. 

The logger did start working though 
```shell
2016-05-09 13:24:47.758043 [36mI[0m [7955:rocketjob main] [36mRocketJob::CLI[0m -- Rails not detected. Running standalone: development
2016-05-09 13:24:47.834206 [31mE[0m [7955:rocketjob main rocketjob:12] [31mRocketJob[0m -- Rocket Job shutting down due to exception -- Exception: [1mMongo::ConnectionFailure: Failed to connect to a master node at localhost:27017[0m
/Users/rrobin244/.rvm/gems/ruby-2.2.3/gems/mongo-1.12.5/lib/mongo/mongo_client.rb:417:in `connect'
/Users/rrobin244/.rvm/gems/ruby-2.2.3/gems/mongo-1.12.5/lib/mongo/mongo_client.rb:656:in `setup'
/Users/rrobin244/.rvm/gems/ruby-2.2.3/gems/mongo_ha-1.12.1/lib/mongo_ha/mongo_client.rb:73:in `setup'
/Users/rrobin244/.rvm/gems/ruby-2.2.3/gems/mongo-1.12.5/lib/mongo/mongo_client.rb:179:in `initialize'
/Users/rrobin244/.rvm/gems/ruby-2.2.3/gems/mongo_mapper-0.13.1/lib/mongo_mapper/connection.rb:13:in `new'
/Users/rrobin244/.rvm/gems/ruby-2.2.3/gems/mongo_mapper-0.13.1/lib/mongo_mapper/connection.rb:13:in `connection'
/Users/rrobin244/.rvm/gems/ruby-2.2.3/gems/mongo_mapper-0.13.1/lib/mongo_mapper/connection.rb:27:in `logger'
/Users/rrobin244/.rvm/gems/ruby-2.2.3/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/logger.rb:9:in `logger'
/Users/rrobin244/.rvm/gems/ruby-2.2.3/gems/rocketjob-2.0.0/lib/rocket_job/config.rb:66:in `load!'
/Users/rrobin244/.rvm/gems/ruby-2.2.3/gems/rocketjob-2.0.0/lib/rocket_job/cli.rb:99:in `boot_standalone'
/Users/rrobin244/.rvm/gems/ruby-2.2.3/gems/rocketjob-2.0.0/lib/rocket_job/cli.rb:27:in `run'
/Users/rrobin244/.rvm/gems/ruby-2.2.3/gems/rocketjob-2.0.0/bin/rocketjob:8:in `<top (required)>'
/Users/rrobin244/.rvm/gems/ruby-2.2.3/bin/rocketjob:23:in `load'
/Users/rrobin244/.rvm/gems/ruby-2.2.3/bin/rocketjob:23:in `<main>'
/Users/rrobin244/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/Users/rrobin244/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
2016-05-09 13:25:15.255945 [36mI[0m [9279:rocketjob main] [36mRocketJob::CLI[0m -- Rails not detected. Running standalone: development
2016-05-09 13:25:15.382774 [36mI[0m [9279:rocketjob main] [36mRocketJob::Worker[0m -- Using MongoDB Database: myapp_development
2016-05-09 13:25:15.385558 [36mI[0m [9279:rocketjob main] [36mRocketJob::Worker[0m -- Starting 10 threads
2016-05-09 13:25:15.385796 [36mI[0m [9279:rocketjob main] [36mRocketJob::Worker[0m -- RocketJob Worker started with 10 workers running
2016-05-09 13:25:15.386127 [36mI[0m [9279:rocketjob 001] [36mRocketJob::Worker[0m -- Started
2016-05-09 13:25:15.890451 [36mI[0m [9279:rocketjob 002] [36mRocketJob::Worker[0m -- Started
2016-05-09 13:25:16.391869 [36mI[0m [9279:rocketjob 003] [36mRocketJob::Worker[0m -- Started
2016-05-09 13:25:16.887520 [36mI[0m [9279:rocketjob 004] [36mRocketJob::Worker[0m -- Started
2016-05-09 13:25:17.388787 [36mI[0m [9279:rocketjob 005] [36mRocketJob::Worker[0m -- Started
2016-05-09 13:25:17.888465 [36mI[0m [9279:rocketjob 006] [36mRocketJob::Worker[0m -- Started
2016-05-09 13:25:18.388788 [36mI[0m [9279:rocketjob 007] [36mRocketJob::Worker[0m -- Started
2016-05-09 13:25:18.887930 [36mI[0m [9279:rocketjob 008] [36mRocketJob::Worker[0m -- Started
2016-05-09 13:25:19.390511 [36mI[0m [9279:rocketjob 009] [36mRocketJob::Worker[0m -- Started
2016-05-09 13:25:19.887776 [36mI[0m [9279:rocketjob 010] [36mRocketJob::Worker[0m -- Started
```

**Comment by reidmorrison** [comment]
For the standalone config above, please generate the mongo config:

~~~
bundle exec rails generate mongo_mapper:config
~~~

Please try the latest RJMC, looks like there was an asset issue on Rails 4.2. Update Gemfile:
~~~ruby
gem 'rocketjob_mission_control', git: 'https://github.com/rocketjob/rocketjob_mission_control'
~~~

The above should now work correctly in the existing Rails app.

**Comment by rjrobinson** [comment]
Awesome. So I have now gotten the standalone to work. I'm trying to enqueue the hello world job, but im getting a `load_config` no method error.

**Comment by rjrobinson** [comment]
no sure if you want to close, since the original issue has been resolved. I can open another one. I know some projects have some strict guidelines about that stuff.

**Comment by reidmorrison** [comment]
Good catch, we missed the use of the older V1 config api. The docs have now been updated for non-rails / standalone worker installation:

~~~ruby
require 'rocketjob'
require 'yaml'

# Log to development.log
SemanticLogger.add_appender(file_name: 'development.log', formatter: :color)
SemanticLogger.default_level = :debug

# Configure Mongo
RocketJob::Config.load!('development', 'config/mongo.yml')

require_relative 'jobs/hello_world_job'

HelloWorldJob.create!
~~~

**Comment by rjrobinson** [comment]
Awesome. Thanks for the support.  Now that I got that working. I guess the next step is to test it out. Should prove be interesting. I'm going to need my AR models in order to process the jobs.

**Comment by rjrobinson** [comment]
What version of rails should I be using to get the Web UI to work?

**Comment by reidmorrison** [comment]
The Web UI should work with any version of Rails 4 and 5.
Rails 3.2 support would be based on demand.

**Comment by rjrobinson** [comment]
Ok. The mount is still having Layout issues. But, standalone can work for now.

any guides on multi server deployments? 

also. Im sure we can close this ticket now that the silence method has been solved.

**Comment by reidmorrison** [comment]
Added docs for deployment: http://rocketjob.io/deployment.html
